# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Spinn3r
version:      2.00100304
version_from: lib/WWW/Spinn3r.pm
installdirs:  site
requires:
    Class::Accessor:               0
    DateTime:                      0
    LWP::UserAgent:                
    XML::RSS:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
